/*
 * This file is generated by jOOQ.
 */
package manager.task.domians.tables.references


import manager.task.domians.tables.Films



/**
 * The table <code>public.films</code>.
 */
val FILMS: Films = Films.FILMS
