/*
 * This file is generated by jOOQ.
 */
package manager.task.domians.keys


import manager.task.domians.tables.Films
import manager.task.domians.tables.records.FilmsRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val FIRSTKEY: UniqueKey<FilmsRecord> = Internal.createUniqueKey(Films.FILMS, DSL.name("firstkey"), arrayOf(Films.FILMS.CODE), true)
