/*
 * This file is generated by jOOQ.
 */
package manager.task.domians.tables.pojos


import java.io.Serializable
import java.time.LocalDate

import org.jooq.types.DayToSecond


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Films(
    val code: String? = null,
    val title: String? = null,
    val did: Int? = null,
    val dateProd: LocalDate? = null,
    val kind: String? = null,
    val len: DayToSecond? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Films (")

        sb.append(code)
        sb.append(", ").append(title)
        sb.append(", ").append(did)
        sb.append(", ").append(dateProd)
        sb.append(", ").append(kind)
        sb.append(", ").append(len)

        sb.append(")")
        return sb.toString()
    }
}
